In [2]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]
benzersiz_notlar = list(set(notlar))
print(f"Benzersiz Notlar: {benzersiz_notlar}")

# 2. En yüksek ve en düşük notu bulur.
en_yuksek_not = max(benzersiz_notlar)
en_dusuk_not = min(benzersiz_notlar)
print(f"En Yüksek Not: {en_yuksek_not}")
print(f"En Düşük Not: {en_dusuk_not}")

# 3. Notları küçükten büyüğe sıralar.
benzersiz_notlar.sort()
print(f"Sıralanmış Notlar: {benzersiz_notlar}")

Benzersiz Notlar: [100, 92, 85, 76]
En Yüksek Not: 100
En Düşük Not: 76
Sıralanmış Notlar: [76, 85, 92, 100]


In [3]:
def armstrong_kontrol(sayi):
    """
    Bir sayının Armstrong sayısı olup olmadığını kontrol eder.
    """
    sayi_str = str(sayi)
    basamak_sayisi = len(sayi_str)
    toplam = 0
    for rakam in sayi_str:
        toplam += int(rakam) ** basamak_sayisi

    if toplam == sayi:
        return True
    else:
        return False

# Test edelim
sayi1 = 153
sayi2 = 1634
sayi3 = 120

print(f"{sayi1} bir Armstrong sayısı mı? -> {armstrong_kontrol(sayi1)}")
print(f"{sayi2} bir Armstrong sayısı mı? -> {armstrong_kontrol(sayi2)}")
print(f"{sayi3} bir Armstrong sayısı mı? -> {armstrong_kontrol(sayi3)}")

153 bir Armstrong sayısı mı? -> True
1634 bir Armstrong sayısı mı? -> True
120 bir Armstrong sayısı mı? -> False


In [4]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

# 1. Ortak dilleri bulunur
ortak_diller = A.intersection(B)
print(f"Ortak Diller: {ortak_diller}")

# 2. Sadece A'da olan dilleri listeler.
sadece_a_da_olanlar = A.difference(B)
print(f"Sadece A Kümesinde Olan Diller: {sadece_a_da_olanlar}")

# 3. İki kümenin birleşimini alfabetik olarak yazdırır.
birlesim = sorted(list(A.union(B)))
print(f"İki Kümenin Alfabetik Sıralanmış Birleşimi: {birlesim}")

Ortak Diller: {'Python', 'SQL'}
Sadece A Kümesinde Olan Diller: {'R', 'Java'}
İki Kümenin Alfabetik Sıralanmış Birleşimi: ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [5]:
import random
import statistics

# 1. 1-100 arasında 10 rastgele sayı üretir.
rastgele_sayilar = [random.randint(1, 100) for _ in range(10)]
print(f"Üretilen Rastgele Sayılar: {rastgele_sayilar}")

# 2. Bu sayıların ortalamasını ve standart sapmasını hesaplar.
ortalama = statistics.mean(rastgele_sayilar)
standart_sapma = statistics.stdev(rastgele_sayilar)

print(f"Sayıların Ortalaması: {ortalama}")
print(f"Sayıların Standart Sapması: {standart_sapma:.2f}")

Üretilen Rastgele Sayılar: [28, 25, 90, 93, 6, 42, 36, 64, 8, 96]
Sayıların Ortalaması: 48.8
Sayıların Standart Sapması: 34.67


In [6]:
from collections import Counter
def kelime_sayaci(metin):
    """
    Verilen metindeki toplam kelime sayısını, en uzun kelimeyi ve
    en sık geçen kelimeyi döndürür.
    """
    kelimeler = metin.split()

    # Toplam kelime sayısı
    toplam_kelime = len(kelimeler)

    # En uzun kelime
    en_uzun = max(kelimeler, key=len)

    # En sık geçen kelime
    en_sik_gecen = Counter(kelimeler).most_common(1)[0][0]

    return {
        "Toplam Kelime Sayısı": toplam_kelime,
        "En Uzun Kelime": en_uzun,
        "En Sık Geçen Kelime": en_sik_gecen
    }

ornek_metin = "veri bilimi ve yapay zeka günümüzün en popüler alanları arasında yer alan iki önemli disiplindir veri her yerdedir"
sonuc = kelime_sayaci(ornek_metin)
print(sonuc)

{'Toplam Kelime Sayısı': 18, 'En Uzun Kelime': 'disiplindir', 'En Sık Geçen Kelime': 'veri'}


In [7]:
sayilar = [5, 12, 7, 18, 24, 3, 16]

# 1. Sadece çift sayıları filtreleyin.
cift_sayilar = list(filter(lambda x: x % 2 == 0, sayilar))
print(f"Çift Sayılar: {cift_sayilar}")

# 2. Bu sayıların karelerini bulun. (Çift sayıların kareleri)
kareler = list(map(lambda x: x**2, cift_sayilar))
print(f"Çift Sayıların Kareleri: {kareler}")

# 3. Karelerini azalan sırada sıralayın.
azalan_sirali_kareler = sorted(kareler, reverse=True)
print(f"Karelerin Azalan Sırada Sıralanması: {azalan_sirali_kareler}")

Çift Sayılar: [12, 18, 24, 16]
Çift Sayıların Kareleri: [144, 324, 576, 256]
Karelerin Azalan Sırada Sıralanması: [576, 324, 256, 144]


In [8]:
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]

# Listeyi kelime uzunluğuna göre küçükten büyüğe sırala
uzunluga_gore_sirali = sorted(kelimeler, key=lambda kelime: len(kelime))
print(f"Uzunluklarına Göre Sıralanmış Kelimeler: {uzunluga_gore_sirali}")

Uzunluklarına Göre Sıralanmış Kelimeler: ['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [9]:
import re
def metindeki_sayilari_topla(metin):
    """
    Bir string içinde geçen tüm rakamları (sayıları) bulur ve bunların
    toplamını döndürür. Örn: "abc12def3" -> 15
    """
    # \d+ ifadesi bir veya daha fazla basamaktan oluşan sayıları bulur
    sayilar = re.findall(r'\d+', metin)
    # Bulunan string halindeki sayıları integer'a çevirip toplar
    toplam = sum([int(s) for s in sayilar])
    return toplam

# Test edelim
ornek_metin = "Bu üründen 12 adet, diğerinden ise 3 adet aldım. Toplamda 15 yaptı."
print(f"Metindeki sayıların toplamı: {metindeki_sayilari_topla(ornek_metin)}")
print(f"'abc12def3' -> {metindeki_sayilari_topla('abc12def3')}")

Metindeki sayıların toplamı: 30
'abc12def3' -> 15


In [10]:
import numpy as np
# 1. 0-50 arasında rastgele sayılardan oluşan 10 elemanlı bir numpy dizisi
dizi = np.random.randint(0, 51, 10)
print(f"Oluşturulan Numpy Dizisi: {dizi}")

# 2. Dizinin ortalaması, standart sapması ve en büyük değeri
ortalama = dizi.mean()
standart_sapma = dizi.std()
en_buyuk = dizi.max()

print(f"Dizinin Ortalaması: {ortalama}")
print(f"Dizinin Standart Sapması: {standart_sapma:.2f}")
print(f"Dizinin En Büyük Değeri: {en_buyuk}")

Oluşturulan Numpy Dizisi: [32  1 41 22 21 22  1 27 46 34]
Dizinin Ortalaması: 24.7
Dizinin Standart Sapması: 14.20
Dizinin En Büyük Değeri: 46


In [11]:
import numpy as np

# 5x5 boyutunda rastgele 0–1 arasında değerlerden oluşan matris
matris = np.random.rand(5, 5)
print("Orijinal Matris:\n", matris)

# 1. Her sütunun ortalaması
sutun_ortalamalari = matris.mean(axis=0)
print("\nHer Sütunun Ortalaması:", sutun_ortalamalari)

# 2. 0.5'ten büyük olanları 1, küçük/eşit olanları 0 yaparak binary matris oluşturma
binary_matris = (matris > 0.5).astype(int)
print("\nBinary Matris:\n", binary_matris)

Orijinal Matris:
 [[0.60339589 0.11060275 0.38052308 0.82439781 0.04089715]
 [0.01062507 0.9475006  0.93832039 0.83933441 0.26365457]
 [0.04311731 0.30423707 0.73848994 0.87438081 0.54173301]
 [0.99014087 0.66586602 0.0394599  0.01714847 0.27260516]
 [0.02857709 0.83377494 0.97205339 0.83977681 0.97889191]]

Her Sütunun Ortalaması: [0.33517124 0.57239628 0.61376934 0.67900766 0.41955636]

Binary Matris:
 [[1 0 0 1 0]
 [0 1 1 1 0]
 [0 0 1 1 1]
 [1 1 0 0 0]
 [0 1 1 1 1]]


In [12]:
import statistics
import random
from collections import Counter

kitaplar = [
    {"isim": "Veri Bilimi 101", "yazar": "Ali", "tur": "Bilim", "satis": 1200, "yil": 2021},
    {"isim": "Python ile Yapay Zeka", "yazar": "Ayşe", "tur": "Bilim", "satis": 950, "yil": 2020},
    {"isim": "İstatistik Temelleri", "yazar": "Ali", "tur": "Akademik", "satis": 700, "yil": 2019},
    {"isim": "Makine Öğrenmesi", "yazar": "Can", "tur": "Bilim", "satis": 1800, "yil": 2022},
    {"isim": "Veri Görselleştirme", "yazar": "Deniz", "tur": "Sanat", "satis": 400, "yil": 2018},
    {"isim": "Matematiksel Modelleme", "yazar": "Ali", "tur": "Akademik", "satis": 1500, "yil": 2021},
    {"isim": "Bilgi Toplumu", "yazar": "Ayşe", "tur": "Sosyal", "satis": 600, "yil": 2022}
]

# 1. Fonksiyon Yazma
def en_cok_satan(kitap_listesi):
    return max(kitap_listesi, key=lambda x: x['satis'])

def yazar_satislari(kitap_listesi):
    satislar = {}
    for kitap in kitap_listesi:
        yazar = kitap['yazar']
        satis = kitap['satis']
        satislar[yazar] = satislar.get(yazar, 0) + satis
    return satislar

print("--- 1. Fonksiyonlar ---")
print(f"En Çok Satan Kitap: {en_cok_satan(kitaplar)['isim']}")
print(f"Yazar Satışları: {yazar_satislari(kitaplar)}")

# 2. Liste ve Küme İşlemleri
tum_turler = {kitap['tur'] for kitap in kitaplar}
binden_fazla_satanlar = [kitap['isim'] for kitap in kitaplar if kitap['satis'] > 1000]

print("\n--- 2. Liste ve Küme İşlemleri ---")
print(f"Tüm Kitap Türleri: {tum_turler}")
print(f"1000'den Fazla Satan Kitaplar: {binden_fazla_satanlar}")

# 3. Lambda / Filter / Map Kullanımı
yeni_kitaplar = list(filter(lambda x: x['yil'] > 2020, kitaplar))
artirilmis_satislar = list(map(lambda x: x['satis'] * 1.1, kitaplar))
satisa_gore_sirali = sorted(kitaplar, key=lambda x: x['satis'], reverse=True)

print("\n--- 3. Lambda / Filter / Map ---")
print("2020'den Sonra Çıkan Kitaplar:")
for kitap in yeni_kitaplar:
    print(f"- {kitap['isim']} ({kitap['yil']})")

print(f"\n%10 Artırılmış Satış Adetleri: {[f'{s:.1f}' for s in artirilmis_satislar]}")

print("\nSatış Miktarına Göre Sıralanmış Kitaplar:")
for kitap in satisa_gore_sirali:
    print(f"- {kitap['isim']} ({kitap['satis']})")

# 4. İstatistiksel Analiz
satis_adetleri = [kitap['satis'] for kitap in kitaplar]
ortalama_satis = statistics.mean(satis_adetleri)
standart_sapma_satis = statistics.stdev(satis_adetleri)

turler = [kitap['tur'] for kitap in kitaplar]
en_cok_satan_tur = Counter(turler).most_common(1)[0][0]

print("\n--- 4. İstatistiksel Analiz ---")
print(f"Ortalama Satış Adedi: {ortalama_satis:.2f}")
print(f"En Çok Satış Yapan Tür: {en_cok_satan_tur}")
print(f"Satışların Standart Sapması: {standart_sapma_satis:.2f}")

# 5. Ekstra (Zorlayıcı): Train/Test Simülasyonu
print("\n--- 5. Train/Test Simülasyonu ---")
# Veriyi %70 train, %30 test olarak ayır
test_eleman_sayisi = int(len(kitaplar) * 0.3)
train_set = random.sample(kitaplar, k=len(kitaplar) - test_eleman_sayisi)
test_set = [kitap for kitap in kitaplar if kitap not in train_set]

print(f"Train setinde {len(train_set)}, test setinde {len(test_set)} kitap var.")

# Eğitim verisinden yazarların ortalama satışını hesaplar
yazar_ortalamalari = {}
yazar_satis_listeleri = {yazar: [] for yazar in yazar_satislari(train_set).keys()}

for kitap in train_set:
    yazar_satis_listeleri[kitap['yazar']].append(kitap['satis'])

for yazar, satislar in yazar_satis_listeleri.items():
    if satislar:
        yazar_ortalamalari[yazar] = statistics.mean(satislar)

print("\nEğitim Setindeki Yazar Ortalama Satışları:", yazar_ortalamalari)

# Test verisinde, hangi kitapların satışlarının bu ortalamanın üzerinde olduğunu kontrol et
print("\nTest Seti Analizi:")
for kitap in test_set:
    yazar = kitap['yazar']
    satis = kitap['satis']
    if yazar in yazar_ortalamalari:
        ortalama = yazar_ortalamalari[yazar]
        if satis > ortalama:
            print(f"- '{kitap['isim']}' kitabının satışı ({satis}), yazarının ortalamasının ({ortalama:.2f}) üzerindedir.")
        else:
             print(f"- '{kitap['isim']}' kitabının satışı ({satis}), yazarının ortalamasının ({ortalama:.2f}) altında veya eşittir.")
    else:
        print(f"- '{kitap['isim']}' kitabının yazarı ({yazar}) eğitim setinde bulunmuyor, karşılaştırma yapılamadı.")

--- 1. Fonksiyonlar ---
En Çok Satan Kitap: Makine Öğrenmesi
Yazar Satışları: {'Ali': 3400, 'Ayşe': 1550, 'Can': 1800, 'Deniz': 400}

--- 2. Liste ve Küme İşlemleri ---
Tüm Kitap Türleri: {'Sanat', 'Akademik', 'Sosyal', 'Bilim'}
1000'den Fazla Satan Kitaplar: ['Veri Bilimi 101', 'Makine Öğrenmesi', 'Matematiksel Modelleme']

--- 3. Lambda / Filter / Map ---
2020'den Sonra Çıkan Kitaplar:
- Veri Bilimi 101 (2021)
- Makine Öğrenmesi (2022)
- Matematiksel Modelleme (2021)
- Bilgi Toplumu (2022)

%10 Artırılmış Satış Adetleri: ['1320.0', '1045.0', '770.0', '1980.0', '440.0', '1650.0', '660.0']

Satış Miktarına Göre Sıralanmış Kitaplar:
- Makine Öğrenmesi (1800)
- Matematiksel Modelleme (1500)
- Veri Bilimi 101 (1200)
- Python ile Yapay Zeka (950)
- İstatistik Temelleri (700)
- Bilgi Toplumu (600)
- Veri Görselleştirme (400)

--- 4. İstatistiksel Analiz ---
Ortalama Satış Adedi: 1021.43
En Çok Satış Yapan Tür: Bilim
Satışların Standart Sapması: 506.51

--- 5. Train/Test Simülasyonu ---
Trai